runtime: php55
api_version: 1

handlers:
- url: /
  script: index.php
  
# Serve images/js/css as static resources.
- url: /(.+\.(gif|png|jpg|js|css|jpeg|tiff|ico|svg|woff|eot))$
  static_files: \1
  upload: .+\.(gif|png|jpg|js|css|jpeg|tiff|ico|svg|woff|eot)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1
  
  
  env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/newflipkartiot:asia-south1:newflipkartiot;dbname=newflipkartiot
  MYSQL_USER: quintaflipkart
  MYSQL_PASSWORD: quint(%#&^IOT)_3842
