runtime: php55
api_version: 1

handlers:
- url: /
  script: index.php
  
# Serve images/js/css as static resources.
- url: /(.+\.(gif|png|jpg|js|css|jpeg|tiff))$
  static_files: \1
  upload: .+\.(gif|png|jpg|js|css|jpeg|tiff)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1
